/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-12-30 06:41:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java .util.Iterator;
import java.util.ArrayList;
import java.sql.*;
import example_Ajax.*;

public final class dropdown_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
ResultSet resultset =null;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("    <TITLE>Select element drop down box</TITLE>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction fn()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar coutry=document.getElementById(\"country\");\r\n");
      out.write("\t\tvar states=documment.getElementById(\"states\")\r\n");
      out.write("\t\tvar stateList = states[coutry.value];\r\n");
      out.write("\t\tchangeSelect('state', stateList, stateList);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeSelect(fieldID, newOptions, newValues) {\r\n");
      out.write("\t\t  selectField = document.getElementById(fieldID);\r\n");
      out.write("\t\t  selectField.options.length = 0;\r\n");
      out.write("\t\t  for (i=0; i<newOptions.length; i++) {\r\n");
      out.write("\t\t    selectField.options[selectField.length] = new Option(newOptions[i], newValues[i]);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<form name=\"myform\" ACTION=\"\" METHOD=\"POST\">\r\n");
      out.write("<BODY BGCOLOR=##f89ggh>\r\n");
      out.write("<table border=1>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Country:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<select type=\"dropdown\" name=\"country\" id=\"country\" onchannge=\"fn()\">\r\n");


DBCountry dbc=new DBCountry();
Citybean bean=null;
ArrayList<Citybean> array=new ArrayList<Citybean>(); 
array=dbc.getDetails();
 Iterator itr=array.iterator();
while(itr.hasNext())
{
	bean=(Citybean)itr.next();
 
      out.write("\r\n");
      out.write(" <option value=>");
      out.print(bean.getCountry());
      out.write('\r');
      out.write('\n');
      out.write('	');
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("   </td></tr></table>\r\n");
      out.write("   <table border=1>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("States:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<select type=\"dropdown\" name=\"states\" id=\"states\" >\r\n");
      out.write("\r\n");

String country=request.getParameter("country");

DBCountry dbs=new DBCountry();
Citybean bean1=null;
ArrayList<Citybean> array1=new ArrayList<Citybean>(); 
array1=dbs.getDetails1(country);
 Iterator itr1=array1.iterator();
while(itr1.hasNext())
{
	bean1=(Citybean)itr1.next();
 
      out.write("\r\n");
      out.write(" <option value=>");
      out.print(bean1.getStates());
      out.write('\r');
      out.write('\n');
      out.write('	');
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("   </td></tr></table>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</form>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
